# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: python EmpApp.py
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 80
    onOpen: open-preview
